# Multi-Timeframe CipherB Analysis System

system:
  name: "Multi-Timeframe CipherB System"
  version: "3.0"
  timeframes: ["6h", "8h", "12h"]

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

market_data:
  source: "coinmarketcap"
  target_coins: 500
  method: "top_by_rank"
  update_frequency: "6_hours"
  rank_range: "1-500"

alerts:
  freshness_minutes: 90
  batch_size: 30

suppression:
  window_hours: 24
  cleanup_hours: 72

exchanges:
  primary: "bingx"
  fallback: "kucoin"
  rate_limit: 0.3
  timeout: 30
