# Multi-Timeframe Analysis System Configuration
system:
  name: "Multi-Timeframe CipherB System"
  version: "3.0"
  timeframes: ["6h", "8h", "12h"]
  timezone: "+05:30"  # IST

# CipherB Indicator Settings (Same as 15m system)
cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
  heikin_ashi: true

# Market Data Configuration
market_data:
  source: "coinmarketcap"
  min_market_cap: 50000000   # $50M minimum
  min_volume_24h: 20000000   # $20M minimum
  refresh_hours: 12
  min_candles_required: 100

# Advanced Suppression Logic
suppression:
  enabled: true
  cascade_order: ["6h", "8h", "12h"]
  reset_on_opposite: true
  max_suppression_hours: 72
  state_file: "cache/suppression-state.json"

# Alert Configuration
alerts:
  channel_name: "Day-Trader"
  include_timeframe_source: true
  batch_signals: true
  max_message_length: 4000
  include_charts: true

# Exchange Configuration (Same as 15m)
exchanges:
  primary:
    name: "bingx"
    rate_limit: 300
    timeout: 30
  fallback:
    name: "kucoin"
    rate_limit: 500 
    timeout: 30

# Processing Configuration
processing:
  batch_size: 25
  rate_limit_delay: 0.4
  max_analysis_time: 900  # 15 minutes max
  retry_attempts: 3

# Cache Configuration
cache:
  suppression_state: "cache/suppression-state.json"
  analysis_cache_6h: "cache/multi-6h-cache.json"
  analysis_cache_8h: "cache/multi-8h-cache.json"
  analysis_cache_12h: "cache/multi-12h-cache.json"
  cleanup_hours: 72
