# 15-Minute CipherB + CTO Confirmation System

system:
  name: "CipherB + CTO 15m System"
  version: "3.0"
  timeframe: "15m"

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

cto:
  spacing: 3
  signal_length: 20
  filter_type: "PhiSmoother"
  post_smooth_length: 1
  upper_trim: 0
  lower_trim: 0
  phase: 3.7
  overbought_threshold: 70
  oversold_threshold: -70

market_data:
  source: "coinmarketcap"
  target_coins: 100
  method: "top_by_rank"

alerts:
  cooldown_hours: 4
  freshness_minutes: 25
  batch_size: 20

exchanges:
  primary: "bingx"
  fallback: "kucoin"
  rate_limit: 0.3
  timeout: 30
