# 15-Minute CipherB + CTO System Configuration
system:
  name: "CipherB + CTO 15-Minute System"
  version: "3.0"
  timeframe: "15m"
  timezone: "+05:30"  # IST

# CipherB Indicator Settings (Your Validated Parameters)
cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
  heikin_ashi: true

# Composite Trend Oscillator Settings
cto:
  spacing: 3
  signal_length: 20
  filter_type: "PhiSmoother"
  post_smooth_length: 1
  upper_trim: 0
  lower_trim: 0
  phase: 3.7
  # Modified thresholds (changed from ±75 to ±70)
  oversold_threshold: -70
  overbought_threshold: 70

# Market Data Configuration
market_data:
  source: "coinmarketcap"
  target_coins: 100  # Top 100 by market cap ranking
  refresh_hours: 12
  min_candles_required: 100

# Trading Logic
signals:
  confirmation_required: true
  cooldown_hours: 4  # 4-hour cooldown for same direction
  immediate_opposite: true  # Immediate alerts for opposite direction

# Alert Configuration  
alerts:
  channel_name: "15-Minute Analysis"
  batch_signals: true
  max_message_length: 4000
  include_charts: true
  chart_timeframe: "15"

# Exchange Configuration
exchanges:
  primary:
    name: "bingx"
    rate_limit: 300  # milliseconds
    timeout: 30
  fallback:
    name: "kucoin" 
    rate_limit: 500
    timeout: 30

# Processing Configuration
processing:
  batch_size: 20
  rate_limit_delay: 0.3
  max_analysis_time: 600  # 10 minutes max
  retry_attempts: 3

# Cache Configuration
cache:
  deduplication_file: "cache/dedup-15m.json"
  analysis_cache: "cache/system-15m-cache.json"
  cleanup_hours: 24
