# 30-Minute CipherB + CTO Configuration

# CipherB Indicator Settings
cipherb:
  ap_length: 10
  ma_length: 21
  source: "hlc3"
  
# Composite Trend Oscillator Settings
cto:
  spacing: 3
  signal_length: 20
  filter_type: "PhiSmoother"
  post_smooth_length: 1
  upper_trim: 0
  lower_trim: 0
  phase: 3.7
  overbought_threshold: 70
  oversold_threshold: -70

# Alert Configuration
alerts:
  batch_size: 30
  timeout: 300

# Exchange Settings
exchanges:
  rate_limit: 0.1
  timeout: 30

# System Settings
system:
  name: "30-Minute CipherB + CTO"
  version: "3.0"
  timeframe: "30m"
  confirmation_required: true
  deduplication_hours: 4
  freshness_minutes: 30
