# EMA 15M Analysis Configuration
# Switch between analyses by commenting/uncommenting the 'enabled' field

analysis:
  ema_12_21:
    enabled: true          # Set to false to disable 12/21 analysis
    ema_short: 12
    ema_long: 21
    cooldown_hours: 6
    description: "Fast EMA crossover for quick signals"

  ema_21_50:
    enabled: false         # Set to true to enable 21/50 analysis  
    ema_short: 21
    ema_long: 50
    cooldown_hours: 12
    description: "Standard EMA crossover for reliable signals"

system:
  timeframe: "15m"
  freshness_minutes: 30    # Only alert if crossover happened within 30 minutes
  data_limit: 200          # Number of candles to fetch for EMA accuracy
  max_workers: 10          # Concurrent analysis threads

# To switch analysis:
# 1. Set desired analysis enabled: true
# 2. Set other analysis enabled: false  
# 3. Commit changes - next run will use new config
