name: 15-Minute CipherB + CTO Analysis

on:
  schedule:
    # Only keep primary schedule - remove backup to prevent duplicates
    - cron: '1,16,31,46 * * * *'
  workflow_dispatch:

jobs:
  analysis_15m:
    runs-on: ubuntu-latest
    timeout-minutes: 18
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run 15m Analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_15M_CHAT_ID: ${{ secrets.TELEGRAM_15M_CHAT_ID }}
        BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
        BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      run: python src/analyzer_6h.py
      
    - name: Commit Cache Updates
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add cache/
        git commit -m "Update 15m analysis cache [skip ci]" || echo "No changes"
        git push || echo "Push failed"
